version: "3"
services:

  api:
    build: ./api
    restart: always
    depends_on:
      - mongodb

    ports:
      - 8080:8080

  crawler:
    build: ./crawler
    restart: always
    depends_on:
      - mongodb

    ports:
      - 8081:8081

  mongodb:
      image: mongo
      container_name: mongodb
      restart: always
      volumes:
        - ./data:/data/db

      ports:
        - 27017:27017