@@ -0,0 +1,60 @@
version: "3"
services:

  api:
    build: ./api
    container_name: api
    restart: always
    depends_on:
      - kafka
      - mongodb

    ports:
      - 8080:8080

  crawler:
    build: ./crawler
    container_name: crawler
    restart: always
    environment:
      WAIT_HOSTS: kafka:9092,mongodb:27017
    ports:
      - 8081:8081

  storage:
    build: ./storage
    container_name: storage
    restart: always
    environment:
      WAIT_HOSTS: kafka:9092,mongodb:27071

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka:2.11-1.1.1
    container_name: kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: "mention:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
    volumes:
      - ./data/kafka:/var/run/docker.sock
    depends_on:
      - zookeeper
    ports:
      - 9092
